### ISSUE TITLE
Logical error in custom compare construct for sorting vector<Point2D>

### ISSUE THREAD

**Issue by Deepank308** [dkotsur/FortuneAlgo#1]
https://github.com/dkotsur/FortuneAlgo/blob/62570cbb8f5ca3030f7347ffbf11a6f6487edbad/FortuneAlgo/FortuneAlgo/main.cpp#L112

I think correct expression should be:
```cpp
return (fabs(p1.y - p2.y) < POINT_EPSILON && p1.x < p2.x) || (fabs(p1.y - p2.y) >= POINT_EPSILON && p1.y < p2.y);
```
>

**Comment by dkotsur** [comment]
Thanks, fixed that.
